export const termsAndConditions = `
Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. In mollis nunc sed id semper risus in hendrerit gravida. Facilisi nullam vehicula ipsum a arcu cursus vitae congue mauris. Pharetra sit amet aliquam id diam maecenas ultricies. Urna molestie at elementum eu facilisis. Dictum varius duis at consectetur lorem donec. Ante in nibh mauris cursus mattis molestie. Nisl nunc mi ipsum faucibus vitae aliquet. Dui accumsan sit amet nulla. Posuere morbi leo urna molestie at elementum eu. Habitant morbi tristique senectus et netus et malesuada. Mi eget mauris pharetra et. Velit laoreet id donec ultrices. Eget magna fermentum iaculis eu non diam phasellus vestibulum lorem. Feugiat in ante metus dictum at tempor commodo ullamcorper. Velit dignissim sodales ut eu sem.

Ac turpis egestas maecenas pharetra convallis posuere. Sit amet tellus cras adipiscing enim eu turpis egestas. Tincidunt lobortis feugiat vivamus at. Cursus in hac habitasse platea. Placerat vestibulum lectus mauris ultrices. Nisi vitae suscipit tellus mauris a diam maecenas sed enim. Donec ultrices tincidunt arcu non sodales neque sodales ut. Tincidunt praesent semper feugiat nibh sed pulvinar. Quis viverra nibh cras pulvinar mattis. Tellus mauris a diam maecenas sed enim ut sem. Sit amet luctus venenatis lectus magna fringilla urna. Feugiat in fermentum posuere urna nec.

Enim praesent elementum facilisis leo vel fringilla. Nec feugiat in fermentum posuere. Congue eu consequat ac felis. Lectus quam id leo in vitae turpis massa sed elementum. Magna sit amet purus gravida quis. Etiam sit amet nisl purus in mollis nunc sed id. Accumsan sit amet nulla facilisi morbi tempus. Porttitor rhoncus dolor purus non enim praesent elementum facilisis. Leo duis ut diam quam nulla porttitor massa id. Risus sed vulputate odio ut enim blandit volutpat maecenas. Lacus luctus accumsan tortor posuere. Amet luctus venenatis lectus magna fringilla urna porttitor rhoncus dolor. Nullam vehicula ipsum a arcu cursus vitae. Aliquam ut porttitor leo a diam. Magnis dis parturient montes nascetur. Consequat semper viverra nam libero justo laoreet sit.

Phasellus faucibus scelerisque eleifend donec pretium vulputate sapien. Id aliquet lectus proin nibh. Morbi tristique senectus et netus et. Egestas egestas fringilla phasellus faucibus. Imperdiet dui accumsan sit amet nulla facilisi morbi. Viverra justo nec ultrices dui sapien eget mi proin sed. Diam donec adipiscing tristique risus nec feugiat in fermentum posuere. Vitae sapien pellentesque habitant morbi. Orci sagittis eu volutpat odio facilisis mauris. Eget felis eget nunc lobortis. Felis donec et odio pellentesque. Netus et malesuada fames ac turpis egestas sed tempus urna. Molestie at elementum eu facilisis sed odio morbi quis. Aliquam etiam erat velit scelerisque. Sit amet justo donec enim diam vulputate ut pharetra sit.

Auctor eu augue ut lectus arcu. Nunc sed augue lacus viverra. Cursus mattis molestie a iaculis at erat pellentesque adipiscing commodo. Ut tristique et egestas quis. Malesuada nunc vel risus commodo viverra maecenas. Risus pretium quam vulputate dignissim suspendisse in est. Nulla facilisi etiam dignissim diam. Venenatis tellus in metus vulputate eu scelerisque. Scelerisque eu ultrices vitae auctor eu augue ut lectus. In fermentum posuere urna nec tincidunt praesent semper feugiat. Ut placerat orci nulla pellentesque. Purus gravida quis blandit turpis cursus in. Aliquet sagittis id consectetur purus ut faucibus. Pharetra magna ac placerat vestibulum lectus mauris ultrices. Congue nisi vitae suscipit tellus mauris a diam. Mauris pellentesque pulvinar pellentesque habitant morbi tristique senectus.

Faucibus ornare suspendisse sed nisi. Fusce ut placerat orci nulla pellentesque. Elit duis tristique sollicitudin nibh. Rhoncus aenean vel elit scelerisque mauris pellentesque pulvinar pellentesque. Molestie a iaculis at erat. Egestas fringilla phasellus faucibus scelerisque. Vulputate eu scelerisque felis imperdiet. Erat nam at lectus urna duis convallis convallis tellus id. Cursus in hac habitasse platea dictumst quisque sagittis purus. Sem integer vitae justo eget magna. A pellentesque sit amet porttitor eget dolor morbi non. Cras pulvinar mattis nunc sed blandit libero volutpat sed. Vestibulum sed arcu non odio euismod. Sed viverra ipsum nunc aliquet bibendum. Faucibus interdum posuere lorem ipsum dolor. Proin libero nunc consequat interdum varius sit amet mattis. Fringilla phasellus faucibus scelerisque eleifend.

Adipiscing vitae proin sagittis nisl rhoncus mattis rhoncus urna. Faucibus vitae aliquet nec ullamcorper. Vestibulum mattis ullamcorper velit sed ullamcorper morbi tincidunt ornare massa. Sem viverra aliquet eget sit amet tellus cras adipiscing. Tincidunt ornare massa eget egestas purus viverra accumsan. Ac tincidunt vitae semper quis lectus nulla at volutpat. Elit ut aliquam purus sit amet luctus venenatis lectus magna. Nibh tellus molestie nunc non blandit. Non odio euismod lacinia at. Sit amet commodo nulla facilisi nullam. Blandit aliquam etiam erat velit scelerisque. Ullamcorper sit amet risus nullam eget. Ultrices neque ornare aenean euismod elementum nisi quis. Nam at lectus urna duis convallis convallis tellus id interdum.

Diam ut venenatis tellus in metus vulputate eu scelerisque felis. Mauris rhoncus aenean vel elit scelerisque mauris pellentesque pulvinar pellentesque. Molestie ac feugiat sed lectus vestibulum mattis ullamcorper velit. Ut porttitor leo a diam sollicitudin tempor id eu nisl. Enim ut tellus elementum sagittis vitae. Nec nam aliquam sem et tortor. Nisl suscipit adipiscing bibendum est ultricies integer quis auctor. Dignissim sodales ut eu sem. Justo eget magna fermentum iaculis eu non. Est sit amet facilisis magna etiam tempor orci. Dui accumsan sit amet nulla facilisi morbi tempus iaculis urna. Semper auctor neque vitae tempus quam. Volutpat consequat mauris nunc congue nisi vitae. Tortor condimentum lacinia quis vel eros.

Dui ut ornare lectus sit. Commodo elit at imperdiet dui accumsan sit amet nulla facilisi. Vestibulum morbi blandit cursus risus at ultrices mi tempus. In mollis nunc sed id semper risus in. Elementum facilisis leo vel fringilla est. Condimentum id venenatis a condimentum vitae sapien pellentesque. Posuere lorem ipsum dolor sit amet consectetur. Velit scelerisque in dictum non. Eleifend mi in nulla posuere sollicitudin aliquam ultrices sagittis. Commodo quis imperdiet massa tincidunt nunc. Vitae tortor condimentum lacinia quis vel eros donec ac. Mauris rhoncus aenean vel elit scelerisque. Vitae proin sagittis nisl rhoncus mattis rhoncus. Cursus euismod quis viverra nibh cras pulvinar mattis nunc. Elementum eu facilisis sed odio morbi quis commodo. Est velit egestas dui id ornare arcu odio ut.

Natoque penatibus et magnis dis parturient montes nascetur ridiculus. Massa tempor nec feugiat nisl pretium fusce id. In metus vulputate eu scelerisque felis imperdiet proin. Eget mi proin sed libero enim sed faucibus turpis. Fringilla urna porttitor rhoncus dolor purus non enim praesent elementum. Faucibus vitae aliquet nec ullamcorper sit amet. Quis varius quam quisque id diam vel. Sit amet purus gravida quis blandit. Proin libero nunc consequat interdum varius sit amet. Eu feugiat pretium nibh ipsum consequat. Vitae semper quis lectus nulla at volutpat. Dictum at tempor commodo ullamcorper a. Ut etiam sit amet nisl purus in mollis nunc sed.
`;

export const privacyPolicy = `Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ac feugiat sed lectus vestibulum mattis ullamcorper velit sed ullamcorper. Nunc faucibus a pellentesque sit amet porttitor eget dolor. Ipsum dolor sit amet consectetur adipiscing. Nunc mi ipsum faucibus vitae aliquet nec ullamcorper sit amet. Viverra accumsan in nisl nisi scelerisque eu ultrices vitae. Tellus integer feugiat scelerisque varius morbi enim nunc. Ultricies mi quis hendrerit dolor magna eget est lorem. Sed augue lacus viverra vitae. Eget velit aliquet sagittis id consectetur purus ut faucibus. Pretium fusce id velit ut tortor pretium viverra suspendisse potenti.

Elit pellentesque habitant morbi tristique senectus et netus et malesuada. Mattis enim ut tellus elementum sagittis vitae et leo duis. Dignissim convallis aenean et tortor at risus viverra. Nunc aliquet bibendum enim facilisis gravida neque convallis a cras. Viverra vitae congue eu consequat. Sollicitudin aliquam ultrices sagittis orci a scelerisque purus semper. In cursus turpis massa tincidunt. Id donec ultrices tincidunt arcu non sodales neque. Mi in nulla posuere sollicitudin aliquam. Sagittis id consectetur purus ut faucibus. Est ultricies integer quis auctor elit sed. Tincidunt dui ut ornare lectus. Urna cursus eget nunc scelerisque viverra mauris. Accumsan tortor posuere ac ut consequat semper viverra nam libero. Nulla facilisi morbi tempus iaculis urna id.

Aliquet risus feugiat in ante metus dictum at tempor commodo. In fermentum posuere urna nec tincidunt praesent semper. Ultricies integer quis auctor elit sed vulputate mi. Est ante in nibh mauris. Rhoncus dolor purus non enim praesent elementum facilisis leo. Blandit massa enim nec dui nunc mattis enim. Dictum varius duis at consectetur. Magna etiam tempor orci eu lobortis elementum. At volutpat diam ut venenatis tellus in metus vulputate. Diam phasellus vestibulum lorem sed risus. At risus viverra adipiscing at in tellus. Bibendum ut tristique et egestas quis. Dolor sit amet consectetur adipiscing. Molestie ac feugiat sed lectus vestibulum mattis ullamcorper velit sed. Malesuada fames ac turpis egestas maecenas. Nulla aliquet enim tortor at auctor urna nunc id. Et malesuada fames ac turpis. Nam aliquam sem et tortor consequat id. Lectus quam id leo in vitae turpis massa sed. Ut eu sem integer vitae justo eget.

Dignissim cras tincidunt lobortis feugiat vivamus at augue eget. Viverra vitae congue eu consequat ac felis donec et odio. Vel orci porta non pulvinar neque laoreet suspendisse interdum consectetur. Felis eget nunc lobortis mattis aliquam faucibus purus in massa. Massa tincidunt dui ut ornare. Gravida cum sociis natoque penatibus et magnis dis parturient. Purus ut faucibus pulvinar elementum integer enim. Et malesuada fames ac turpis egestas maecenas pharetra convallis posuere. Enim sed faucibus turpis in. Elementum pulvinar etiam non quam. Pellentesque dignissim enim sit amet venenatis urna cursus. Feugiat in ante metus dictum at.`;
